//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCHCF_DatabaseFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOPDONGCC
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HOPDONGCC()
        {
            this.CHITIETHDCCs = new HashSet<CHITIETHDCC>();
        }
    
        public string MaHDCC { get; set; }
        public string MaNCC { get; set; }
        public Nullable<System.DateTime> NgayHD { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETHDCC> CHITIETHDCCs { get; set; }
        public virtual NHACUNGCAP NHACUNGCAP { get; set; }
    }
}
